# Generated by Django 4.2.9 on 2024-09-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user_name',
            new_name='user',
        ),
    ]
